name: Sync with Upstream
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Add upstream remote
        run: git remote add upstream https://github.com/Kachavi/React-Chatapp.git
        
      - name: Fetch upstream changes
        run: git fetch upstream
      
      - name: Merge upstream changes
        run: git merge upstream/main
      
      - name: Push changes to forked repo
        run: |
          git push origin main
